#base image for running python django applications that can connect to postgres
FROM python:3.7-alpine

COPY . /app/
WORKDIR /app/

RUN apk update -qq && \
    #required to connect to postgres db
    apk add postgresql-libs && \
    apk add --virtual .build-deps gcc python3-dev musl-dev postgresql-dev && \
    #dependency to compile pillow
    apk add build-base python-dev py-pip jpeg-dev zlib-dev  && \    
    python3 -m pip install -r requirements.txt --no-cache-dir && \
    apk --purge del .build-deps && \       

EXPOSE 8080 8090
CMD /bin/bash
